// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpupeihfkoyjdqlhijyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwdXBlaWhma295amRxbGhpanliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMzcyMjgsImV4cCI6MjA2OTYxMzIyOH0.YxH1kZIbzzXZ2BIo2kYf_hnemIHCZxDOjSbzXEMlvAE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});